services:
  postgres:
    image: postgres:15
    container_name: ancord_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-ancord_db}
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ancord_backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Важно: внутри Docker бэкенд стучится к базе по имени контейнера "postgres" (порт 5432)
      DB_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secretpassword}@postgres:5432/${POSTGRES_DB:-ancord_db}?sslmode=disable
      JWT_KEY: ${JWT_KEY:-super_secret_key_123}
      PORT: 8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ancord_frontend
    ports:
      - "5173:80" # Фронт будет доступен на localhost:5173
    depends_on:
      - backend

volumes:
  pgdata:
