DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS chat_members CASCADE;

DROP INDEX IF EXISTS idx_messages_chat_id;
DROP INDEX IF EXISTS idx_chat_members_user_id;